language = "C"
header = '''

#if C_FOR_GO_WORKAROUNDS
// c-for-go doesn't grok `stdint.h`, even with the help
// of an external cc, so, here we are, stdint replacement:

typedef unsigned char uint8_t;
typedef unsigned long int uint32_t;
typedef unsigned long long int int64_t;
typedef unsigned long long int uintptr_t;
typedef signed long int int32_t;
#else // C_FOR_GO_WORKAROUNDS

#include <stdlib.h>
#include <stdint.h>

#endif // C_FOR_GO_WORKAROUNDS
'''
include_guard = "husk"
includes = []
no_includes = true

[defines]
"target_os = windows" = "TARGET_OS_WINDOWS"
"target_os = linux" = "TARGET_OS_LINUX"
"target_os = macos" = "TARGET_OS_MACOS"
